### ISSUE TITLE
exited: ruby (exit status 1; not expected)

### ISSUE THREAD

**Issue by farisdurrani** [scotti-fletcher/peek-apex#1]
## Main error: `exited: ruby (exit status 1; not expected)`

I can't get the peek-apex running using the instructions you provided on [your website](https://redthunder.blog/2023/03/20/oci-iam-domains-user-access-review/). My tenancy is using OCI IAM Domains and I am using an OCI profile with full tenancy admin privileges. Even after waiting for 30 mins, the terminal does not update and `http://localhost:4567` remains inaccessible with the message:

```sh
curl: (56) Recv failure: Connection reset by peer
```

The full error and log are attached below.

## Environment

- OS: Oracle Linux Server 8.10 (x86-64) on Oracle Cloud compute instance
- Docker: Docker version 26.1.3, build b72abbb

## Error

```sh
➜  test354543 docker run -it --name peek \
--mount type=bind,source=/home/opc/.oci,target=/root/.oci/,readonly \
-e OCI_TENANCY_OCID='ocid1.tenancy.oc1..aaaaaaaanw5mqd2vwixrysmytenancycompartmentocidpq' \
-e OCI_PROFILE_NAME='fdurrani' \
-e TOOLTIP_LINE_PX=20 \
-p 4567:4567 \
--rm scottfletcher/peek-domain
2024-07-19T02:29:43.304005Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2024-07-19T02:29:43.322449Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
2024-07-19T02:29:54.754342Z mysqld_safe mysqld from pid file /var/lib/mysql/ac7f12a1c378.pid ended
/usr/lib/python3/dist-packages/supervisor/options.py:470: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2024-07-19 02:30:03,553 INFO Set uid to user 0 succeeded
2024-07-19 02:30:03,557 INFO RPC interface 'supervisor' initialized
2024-07-19 02:30:03,557 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-07-19 02:30:03,557 INFO supervisord started with pid 207
2024-07-19 02:30:04,559 INFO spawned: 'mysqld' with pid 209
2024-07-19 02:30:04,561 INFO spawned: 'ruby' with pid 210
2024-07-19 02:30:05,736 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-19 02:30:05,736 INFO success: ruby entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-07-19 02:30:07,037 INFO exited: ruby (exit status 1; not expected)
```

![image](https://github.com/user-attachments/assets/f17915bc-455a-41bd-a19f-98ff209b06d3)

## Also didn't work on MacOS

Separately trying on my personal MacOS v14.5 on the Apple silicon M-chip, this slightly different error came up. The only difference in the docker run command is that `source=/home/opc/.oci` becomes `source=/Users/fdurrani/.oci` since that's how the MacOS directory is set up.

![image](https://github.com/user-attachments/assets/54916d6e-f409-47ca-a03f-22315b1e13ff)

@scotti-fletcher

**Comment by scotti-fletcher** [comment]
Hi There, apologies for the late reply. 

I believe this runs on intel processors only as I never compiled for Arm chips (I also use a Mac)

To help me further, can you spin up the container again then shell into the container 

docker exec -it <container_id> bash

then trigger the ruby process manually?

ruby /peek/iam_visualiser.rb -o 0.0.0.0

I've just run this today and can confirm it still works.

Cheers

**Comment by farisdurrani** [comment]
## SOLVED!

With some tweaks thanks to your suggestions, I am now able to run the app on Docker on my Macbook M2 laptop and access it on `http://localhost:4567`.

## Running on M2 chip

While yes, the terminal did want about running the app on an ARM chip (see below), it's ultimately not the real problem.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/684a5f0b-8d24-4ef3-a8a0-835ada876752">

## Diagnosing the Docker container

Running `ruby /peek/iam_visualiser.rb -o 0.0.0.0` in the Docker container as you suggested pointed to another problem related to the config file. 

Specifically, I ran into two issues: 
1) Having invalid profile entries (I have access to multiple OCI tenancies as part of my job, so my DEFAULT entry is always gibberish and I had to put a valid file path)
2) Not mounting the SSH private keys in the Docker run command

![image](https://github.com/user-attachments/assets/950704a5-8ef1-4c4b-870d-d9c50b7f048c)
<img width="697" alt="image" src="https://github.com/user-attachments/assets/51f2fdab-f231-46f7-b102-497a226775d6">


## The solution

Having access to the `~/.oci/config` is not enough. The app needs access to all the SSH keys used as well. In my case, I had to add another mount target to read the SSH key file.

See the second `--mount` line.

```sh
docker run -it --name peek \
--mount type=bind,source=/Users/fdurrani/.oci/,target=/root/.oci/,readonly \
--mount type=bind,source=/Users/fdurrani/.oci/id_rsa.pem,target=/root/.oci/id_rsa.pem,readonly \
-e OCI_TENANCY_OCID='ocid1.tenancy.oc1.. aaaaaaaanw5mqd2vwixrysmytenancycompartmentocidpq' \
-e OCI_PROFILE_NAME='fdurrani' \
-e TOOLTIP_LINE_PX=20 \
-p 4567:4567 \
--rm scottfletcher/peek-domain
```

And now it shows!

![image](https://github.com/user-attachments/assets/845d4afa-953b-4a7e-aedb-a0ff25dcb2e6)

You can close this issue now.

**Comment by scotti-fletcher** [comment]
Great! That's awesome!
